--입양후기게시판
DROP VIEW POST_VIEW;
DROP SEQUENCE POST_COMMENT_TB_SEQ;
DROP TRIGGER POST_COMMENT_TB_TRG;
DROP TABLE POST_COMMENT_TB;
DROP SEQUENCE POST_TB_SEQ;
DROP TRIGGER POST_TB_TRG;
DROP TABLE POST_TB;

CREATE TABLE POST_TB
(
     ID         NUMBER CONSTRAINT PK_POST_TB_ID PRIMARY KEY,
     TITLE      VARCHAR2(100) NOT NULL,
     WRITER     VARCHAR2(40) NOT NULL,
     CONTENT    VARCHAR2(4000),
     REGDATE    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
     FILES      VARCHAR2(4000) DEFAULT NULL,
     HIT		NUMBER DEFAULT 0 NOT NULL,
     PUB        NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE SEQUENCE POST_TB_SEQ;

CREATE OR REPLACE TRIGGER POST_TB_TRG
BEFORE INSERT ON POST_TB 
FOR EACH ROW 
BEGIN
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT POST_TB_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

CREATE TABLE POST_COMMENT_TB
(
     ID         NUMBER CONSTRAINT PK_POST_COMMENT_TB_ID PRIMARY KEY,
     WRITER 	VARCHAR2(40) NOT NULL,
     CONTENT	VARCHAR2(4000) NOT NULL,
     REGDATE  	TIMESTAMP DEFAULT SYSTIMESTAMP - INTERVAL '1' SECOND NOT NULL,
     POST_ID	NUMBER NOT NULL
);

CREATE SEQUENCE POST_COMMENT_TB_SEQ;

CREATE OR REPLACE TRIGGER POST_COMMENT_TB_TRG
    BEFORE INSERT ON POST_COMMENT_TB
    FOR EACH ROW 
    BEGIN
        BEGIN
            IF INSERTING AND :NEW.ID IS NULL THEN
                SELECT POST_COMMENT_TB_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
            END IF;
        END COLUMN_SEQUENCES;
    END;
/

CREATE VIEW POST_VIEW AS
(
    SELECT P.ID, P.TITLE, P.WRITER, P.REGDATE, P.FILES, P.HIT, P.PUB, COUNT(C.ID) COMMENT_COUNT
    FROM POST_TB P
    LEFT JOIN POST_COMMENT_TB C ON P.ID = C.POST_ID
    GROUP BY P.ID, P.TITLE, P.WRITER, P.CONTENT, P.REGDATE, P.FILES, P.HIT, P.PUB
);
/

ALTER TABLE POST_COMMENT_TB
ADD CONSTRAINT POST_COMMENT_TB_FK FOREIGN KEY (POST_ID) 
REFERENCES POST_TB(ID) ON DELETE CASCADE;
----------------------------------------------------------------------------------------------------

BEGIN
    FOR i IN 1..250 LOOP
        INSERT INTO POST_TB (TITLE, WRITER, CONTENT) VALUES('N_TITLE-'||i, 'N_WRITER-'||i, 'N_CONTENT-'||i);
    END LOOP;
END;
/

INSERT INTO POST_TB (TITLE, WRITER, CONTENT, FILES) VALUES('NN_TITLE', 'NN_WRITER', 'NN_CONTENT', 'dog.jpg, dog.zip');

BEGIN
    FOR i IN 1..250 LOOP
        INSERT INTO POST_COMMENT_TB (WRITER, CONTENT, POST_ID) VALUES('N_WRITER-'||i, 'N_COMMENT-'||i, CEIL(DBMS_RANDOM.VALUE(1,250)));
    END LOOP;
END;
/

COMMIT;

select * from POST_TB;
select * from POST_COMMENT_TB;